name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter analyze --fatal-infos

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: dart format --set-exit-if-changed .

  integration:
    if: ${{false}} ### TODO: add integration test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip xvfb
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Set up environment
        run: |
          sudo apt install -y dbus dbus-x11 gsettings-desktop-schemas
          echo "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$UID/bus" >> $GITHUB_ENV
          echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV
          gsettings set org.gnome.desktop.interface gtk-theme 'Yaru'
        env:
          DEBIAN_FRONTEND: noninteractive
      - run: flutter pub get
      - name: Run flutter test integration_test
        run: xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' flutter test -d linux integration_test

  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: sudo apt update
      - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip
        env:
          DEBIAN_FRONTEND: noninteractive
      - run: flutter pub get
      - run: flutter build linux -v

  macos:
    if: ${{false}} ### TODO: add macos support
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build macos -v

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: sudo apt update
      - run: sudo apt install -y lcov
        env:
          DEBIAN_FRONTEND: noninteractive
      - run: flutter pub get
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  web:
    if: ${{false}} ### TODO: add web support
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build web -v

  windows:
    if: ${{false}} ### TODO: add windows support
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build windows -v
